In [1]:
import sklearn
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
from sklearn import linear_model, preprocessing

In [2]:
data = pd.read_csv("car.data")
print(data.head())

  buying  maint air persons lug_boot safety  class
0  vhigh  vhigh   2       2    small    low  unacc
1  vhigh  vhigh   2       2    small    med  unacc
2  vhigh  vhigh   2       2    small   high  unacc
3  vhigh  vhigh   2       2      med    low  unacc
4  vhigh  vhigh   2       2      med    med  unacc


In [3]:
le = preprocessing.LabelEncoder()
buying = le.fit_transform(list(data["buying"]))
maint = le.fit_transform(list(data["maint"]))
air = le.fit_transform(list(data["air"]))
persons = le.fit_transform(list(data["persons"]))
lug_boot = le.fit_transform(list(data["lug_boot"]))
safety = le.fit_transform(list(data["safety"]))
cls = le.fit_transform(list(data["class"]))

In [4]:
print(buying)
print(air)
print(safety)
print(cls)

[3 3 3 ... 1 1 1]
[0 0 0 ... 3 3 3]
[1 2 0 ... 1 2 0]
[2 2 2 ... 2 1 3]


In [5]:
predict = "class"

X = list(zip(buying, maint, air, persons, lug_boot, safety))
y = list(cls)

In [6]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size = 0.1)

In [21]:
n_neighbors=7
model = KNeighborsClassifier(n_neighbors)

In [22]:
model.fit(x_train, y_train)
acc = model.score(x_test, y_test)
print(acc*100)

93.0635838150289


In [9]:
predicted = model.predict(x_test)
names = ["poor", "average", "good", "vgood"]

In [10]:
for x in range(len(predicted)):
    print("Predicted:", names[predicted[x]], "\tData:", x_test[x], "\tActual:", names[y_test[x]])
    n = model.kneighbors([x_test[x]], n_neighbors, True)
    print("N: ", n)

Predicted: good 	Data: (1, 3, 0, 1, 0, 1) 	Actual: good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.41421356, 1.41421356]]), array([[1029,  444,  195,  619, 1006,  363, 1447,  768,  625]],
      dtype=int64))
Predicted: good 	Data: (1, 2, 2, 1, 0, 1) 	Actual: good
N:  (array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]]), array([[1450, 1274,  871, 1027, 1442,  393,  632, 1412, 1507]],
      dtype=int64))
Predicted: good 	Data: (0, 3, 3, 2, 1, 0) 	Actual: good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.41421356, 1.41421356]]), array([[1417, 1323,  735,   85,  769,   98,  701,  294,  736]],
      dtype=int64))
Predicted: good 	Data: (1, 3, 3, 0, 1, 0) 	Actual: good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.41421356, 1.41421356]]), array([[1066,  708, 1094,  409,   36,  970,  205, 1467,  365]],
      dtype=

Predicted: good 	Data: (1, 0, 3, 1, 2, 1) 	Actual: good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.41421356]]), array([[1206,  611, 1375,  666, 1266,  281,  307, 1394,  687]],
      dtype=int64))
Predicted: poor 	Data: (1, 3, 3, 1, 0, 0) 	Actual: poor
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.41421356, 1.41421356]]), array([[1160,  708,  328,  562,   51, 1066, 1071,  735,  669]],
      dtype=int64))
Predicted: poor 	Data: (1, 0, 1, 2, 1, 0) 	Actual: vgood
N:  (array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]]), array([[1398,  612, 1516,  810, 1256,  508, 1208,  295, 1340]],
      dtype=int64))
Predicted: good 	Data: (1, 3, 0, 2, 1, 2) 	Actual: good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.41421356]]), array([[ 820,  445,  190,  273, 1182,  707,  215,  849,  195]],
      dtype

Predicted: good 	Data: (1, 2, 0, 0, 2, 0) 	Actual: good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.41421356, 1.41421356]]), array([[ 408, 1089, 1040,   18, 1033,  795, 1019, 1301,   44]],
      dtype=int64))
Predicted: poor 	Data: (0, 0, 1, 1, 0, 2) 	Actual: poor
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.41421356, 1.41421356]]), array([[ 547,  495,  102,  302, 1046,  486,   95,  441,  484]],
      dtype=int64))
Predicted: good 	Data: (1, 0, 3, 0, 0, 2) 	Actual: good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.41421356, 1.41421356, 1.41421356]]), array([[ 200,  231,  464,  517,  142, 1280, 1333,  118,  305]],
      dtype=int64))
Predicted: poor 	Data: (0, 1, 3, 1, 1, 0) 	Actual: poor
N:  (array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]]), array([[ 234,  878,  346,  693,  203, 1105,  766,  451,   86]],
      dtype=

N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.41421356, 1.41421356, 1.41421356, 1.41421356]]), array([[ 418, 1233,  800, 1378, 1399, 1511,  248,  853,  254]],
      dtype=int64))
Predicted: good 	Data: (0, 3, 3, 1, 0, 0) 	Actual: good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.41421356,
        1.41421356, 1.41421356, 1.41421356, 1.41421356]]), array([[ 322,  735,  669, 1417,  377, 1243, 1510, 1360,  294]],
      dtype=int64))
Predicted: poor 	Data: (1, 2, 1, 2, 2, 0) 	Actual: average
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.41421356]]), array([[ 516, 1303,  720,  610, 1353,  528,  661,  630,  426]],
      dtype=int64))
Predicted: good 	Data: (0, 0, 1, 1, 1, 2) 	Actual: good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.41421356, 1.41421356]]), array([[ 998,  418, 1003, 1513,  267, 1399, 1170,